"use client";
import {useEffect,useMemo,useState,type ReactNode} from "react";
import Activity from "lucide-react/dist/esm/icons/activity";import Bell from "lucide-react/dist/esm/icons/bell";import Building2 from "lucide-react/dist/esm/icons/building-2";import CalendarPlus from "lucide-react/dist/esm/icons/calendar-plus";import CheckCircle2 from "lucide-react/dist/esm/icons/circle-check";import ChevronDown from "lucide-react/dist/esm/icons/chevron-down";import ChevronLeft from "lucide-react/dist/esm/icons/chevron-left";import ChevronRight from "lucide-react/dist/esm/icons/chevron-right";import CircleHelp from "lucide-react/dist/esm/icons/circle-help";import ClipboardList from "lucide-react/dist/esm/icons/clipboard-list";import Clock3 from "lucide-react/dist/esm/icons/clock-3";import FileSearch from "lucide-react/dist/esm/icons/file-search";import HeartPulse from "lucide-react/dist/esm/icons/heart-pulse";import HomeIcon from "lucide-react/dist/esm/icons/house";import Hospital from "lucide-react/dist/esm/icons/hospital";import Leaf from "lucide-react/dist/esm/icons/leaf";import MapPin from "lucide-react/dist/esm/icons/map-pin";import Plus from "lucide-react/dist/esm/icons/plus";import Search from "lucide-react/dist/esm/icons/search";import ShieldPlus from "lucide-react/dist/esm/icons/shield-plus";import Sparkles from "lucide-react/dist/esm/icons/sparkles";import Stethoscope from "lucide-react/dist/esm/icons/stethoscope";import UserRound from "lucide-react/dist/esm/icons/circle-user-round";
import {api,token,type Department,type Doctor,type Hospital as HospitalType,type Order,type Person,type Schedule} from "./api-client";
type Tab="home"|"guide"|"orders"|"profile";
const statusText:Record<string,string>={pending_payment:"待支付",paid:"已支付",confirmed:"待就诊",completed:"已完成",cancelled:"已取消",refunded:"已退款",expired:"已过期"};
const periodText:Record<string,string>={morning:"上午",afternoon:"下午",evening:"晚上",custom:"自定义"};
export default function Home(){
 const[tab,setTab]=useState<Tab>("home"),[hospitals,setHospitals]=useState<HospitalType[]>([]),[departments,setDepartments]=useState<Department[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[orders,setOrders]=useState<Order[]>([]),[people,setPeople]=useState<Person[]>([]),[selectedDept,setSelectedDept]=useState<number>(),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[toast,setToast]=useState(""),[booking,setBooking]=useState<Doctor>(),[schedules,setSchedules]=useState<Schedule[]>([]),[scheduleId,setScheduleId]=useState<number>(),[loginOpen,setLoginOpen]=useState(false),[phone,setPhone]=useState(""),[code,setCode]=useState(""),[personOpen,setPersonOpen]=useState(false),[personForm,setPersonForm]=useState({name:"",phone:"",idCard:""});
 const loggedIn=Boolean(token.get());const notify=(m:string)=>{setToast(m);setTimeout(()=>setToast(""),2200)};
 const loadPublic=async()=>{setLoading(true);try{const[h,d,docs]=await Promise.all([api.hospitals(),api.departments(),api.doctors()]);setHospitals(h);setDepartments(d);setDoctors(docs)}catch(e){notify(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}};
 const loadPrivate=async()=>{if(!token.get())return;try{const[p,o]=await Promise.all([api.people(),api.orders()]);setPeople(p);setOrders(o)}catch{token.clear();setPeople([]);setOrders([])}};
 useEffect(()=>{void loadPublic();void loadPrivate()},[]);
 const filtered=useMemo(()=>doctors.filter(d=>(!selectedDept||d.departmentId===selectedDept)&&(!query||[d.name,d.specialty,d.hospitalName,d.departmentName].some(x=>x.includes(query)))),[doctors,selectedDept,query]);
 const openProtected=(next:Tab)=>{if(!token.get()){setLoginOpen(true);return}setTab(next);void loadPrivate()};
 const startBooking=async(d:Doctor)=>{if(!token.get()){setLoginOpen(true);return}try{const s=await api.schedules(d.id);setSchedules(s);setScheduleId(s.find(x=>x.availableSlots>0)?.id);setBooking(d)}catch(e){notify(e instanceof Error?e.message:"排班加载失败")}};
 const login=async()=>{try{const result=await api.login(phone,code);if(!["user","merchant_admin","merchant_staff","super_admin"].includes(result.user.role))throw new Error("账号不可用");token.set(result.accessToken);setLoginOpen(false);await loadPrivate();notify("登录成功")}catch(e){notify(e instanceof Error?e.message:"登录失败")}};
 const submitBooking=async()=>{if(!booking||!scheduleId)return;if(!people.length){setPersonForm(x=>({...x,phone}));setPersonOpen(true);return}try{await api.register({registrationPersonId:people.find(x=>x.isDefault)?.id??people[0]!.id,hospitalId:booking.hospitalId,departmentId:booking.departmentId,doctorId:booking.id,scheduleId});setBooking(undefined);await loadPrivate();setTab("orders");notify("预约提交成功")}catch(e){notify(e instanceof Error?e.message:"预约失败")}};
 const addPerson=async()=>{try{await api.addPerson({...personForm,relationship:"self",isDefault:true});setPersonOpen(false);await loadPrivate();notify("就诊人已添加，请再次确认预约")}catch(e){notify(e instanceof Error?e.message:"添加失败")}};
 return <main className="app-shell"><div className="phone"><header className="topbar"><button className="city"><MapPin size={16}/>北京 <ChevronDown size={14}/></button><div className="brand"><span className="brand-mark"><ShieldPlus size={17}/></span><b>安康挂号</b></div><button className="message"><Bell size={22}/></button></header>
 {tab==="home"&&<><section className="hero"><p className="eyebrow">专业医疗 · 安心预约</p><h1>看病不迷路<br/><em>挂号更简单</em></h1><p className="hero-copy">医院、科室、医生与实时号源一站查询</p><button className="search" onClick={()=>setTab("guide")}><Search size={19}/><span>搜索医院、科室、医生或疾病</span></button><div className="hero-art"><div className="cross"><ShieldPlus/></div><div className="pulse"><Activity/></div></div></section>
 <section className="quick-grid"><button onClick={()=>setTab("guide")}><span className="quick-icon blue"><Hospital/></span><b>按医院挂号</b><small>浏览医院列表</small></button><button onClick={()=>setTab("guide")}><span className="quick-icon green"><Stethoscope/></span><b>按医生挂号</b><small>查询医生号源</small></button><button onClick={()=>setTab("guide")}><span className="quick-icon violet"><Sparkles/></span><b>按科室查找</b><small>精准筛选科室</small></button><button onClick={()=>openProtected("orders")}><span className="quick-icon orange"><FileSearch/></span><b>预约记录</b><small>查看我的预约</small></button></section>
 <section className="section department-section"><div className="section-head"><div><p>快速预约</p><h2>可预约科室</h2></div><button onClick={()=>setTab("guide")}>全部科室 <ChevronRight/></button></div><div className="dept-grid">{departments.slice(0,8).map((d,i)=><button key={d.id} onClick={()=>{setSelectedDept(d.id);setTab("guide")}}><span className={`dept-icon ${["mint","blue","pink","yellow","purple","orange","cyan","gray"][i%8]}`}><HeartPulse/></span><b>{d.name}</b></button>)}</div></section>
 <section className="section hospital-section"><div className="section-head"><div><p>医院资源</p><h2>可预约医院</h2></div><button onClick={()=>setTab("guide")}>查看医生 <ChevronRight/></button></div><div className="hospital-scroll">{hospitals.map(h=><button className="hospital-card" key={h.id} onClick={()=>{setQuery(h.name);setTab("guide")}}><span className="hospital-logo"><Building2/></span><div><h3>{h.name}</h3><p><i>{h.level}</i>{h.type??"综合医院"}</p><small>{h.district} · {h.address}</small></div><ChevronRight className="arrow"/></button>)}</div>{!loading&&!hospitals.length&&<Empty text="暂无可预约医院"/>}</section><section className="health-card"><div><span>就诊提示</span><h3>预约前请确认就诊人与排班</h3><p>提交挂号后，请按预约时间携带身份证提前到院。</p></div><div className="leaf"><Leaf/></div></section></>}
 {tab==="guide"&&<section className="subpage"><div className="page-title"><button onClick={()=>setTab("home")}><ChevronLeft/></button><h1>预约挂号</h1><span/></div><div className="modal-search inline-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索医院、医生、科室或擅长"/></div><div className="chips"><button className={!selectedDept?"active":""} onClick={()=>setSelectedDept(undefined)}>全部</button>{departments.map(d=><button className={selectedDept===d.id?"active":""} key={d.id} onClick={()=>setSelectedDept(d.id)}>{d.name}</button>)}</div><div className="doctor-list">{loading?<Empty text="正在加载医生…"/>:filtered.map(d=><article className="doctor-card" key={d.id}><div className="avatar">{d.name.slice(0,1)}<span>医</span></div><div className="doctor-info"><div className="doctor-name"><h3>{d.name}</h3><span>{d.title}</span></div><p className="hospital-name">{d.hospitalName} · {d.departmentName}</p><p className="skill"><b>擅长：</b>{d.specialty||"暂无介绍"}</p><div className="doctor-action"><strong>¥{d.registrationFee}<small> 起</small></strong><button onClick={()=>void startBooking(d)}>查看号源</button></div></div></article>)}{!loading&&!filtered.length&&<Empty text="没有找到匹配的医生"/>}</div></section>}
 {tab==="orders"&&<section className="subpage orders-page"><div className="page-title"><span/><h1>我的预约</h1><CircleHelp/></div><div className="order-tabs"><button className="active">全部预约</button></div>{orders.map(o=><article className="appointment" key={o.id}><div className="appointment-top"><span className="date-box"><b>{new Date(o.visitDate).getDate()}</b><small>{new Date(o.visitDate).getMonth()+1}月</small></span><div><i>{statusText[o.status]??o.status}</i><h3>{o.hospitalName}</h3><p>{o.departmentName} · {o.doctorName} {o.doctorTitle}</p></div></div><div className="appointment-time"><span><Clock3/></span><div><small>就诊安排</small><b>{o.visitDate} · {periodText[o.period]??o.period} · {o.visitNumber}号</b></div></div></article>)}{!orders.length&&<Empty text="暂无预约记录"/>}</section>}
 {tab==="profile"&&<section className="subpage profile-page">{loggedIn?<><div className="profile-hero"><div className="profile-avatar">{phone.slice(-1)||"安"}</div><div><h2>{phone||"已登录用户"}</h2><p>就诊信息由账户安全保存</p></div><button onClick={()=>{token.clear();setPeople([]);setOrders([]);notify("已退出登录")}}>退出</button></div><div className="family"><div className="section-head"><div><p>就诊管理</p><h2>我的就诊人</h2></div><button onClick={()=>setPersonOpen(true)}>添加 <Plus/></button></div>{people.map(p=><div className="family-person" key={p.id}><span>{p.name[0]}</span><div><b>{p.name}</b><small>{p.phone} · {p.idCardMasked}</small></div>{p.isDefault&&<i>默认</i>}</div>)}</div></>:<Empty text="登录后管理就诊人与预约"><button className="confirm" onClick={()=>setLoginOpen(true)}>手机号登录</button></Empty>}</section>}
 <nav className="bottom-nav">{[{id:"home",icon:HomeIcon,label:"首页"},{id:"guide",icon:CalendarPlus,label:"挂号"},{id:"orders",icon:ClipboardList,label:"预约"},{id:"profile",icon:UserRound,label:"我的"}].map(x=><button key={x.id} className={tab===x.id?"active":""} onClick={()=>x.id==="orders"?openProtected("orders"):setTab(x.id as Tab)}><span><x.icon/></span><small>{x.label}</small></button>)}</nav>
 {booking&&<div className="modal-backdrop" onClick={()=>setBooking(undefined)}><div className="booking-sheet" onClick={e=>e.stopPropagation()}><div className="modal-handle"/><div className="booking-doctor"><div className="avatar small">{booking.name[0]}</div><div><h3>{booking.name} <span>{booking.title}</span></h3><p>{booking.hospitalName} · {booking.departmentName}</p></div></div><h3>选择有效排班</h3><div className="date-list">{schedules.map(s=><button key={s.id} disabled={!s.availableSlots} className={scheduleId===s.id?"active":""} onClick={()=>setScheduleId(s.id)}><span>{s.scheduleDate.slice(5)}</span><span>{periodText[s.period]??s.period} · 余{s.availableSlots}</span></button>)}</div>{!schedules.length&&<Empty text="暂无有效排班"/>}<div className="fee-line"><span>挂号费用</span><b>¥{schedules.find(s=>s.id===scheduleId)?.fee??booking.registrationFee}</b></div><button className="confirm" disabled={!scheduleId} onClick={()=>void submitBooking()}>确认预约</button></div></div>}
 {loginOpen&&<Modal title="手机号登录" close={()=>setLoginOpen(false)}><label>手机号<input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="请输入手机号"/></label><div className="code-row"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="6位验证码"/><button onClick={async()=>{try{const x=await api.sendSms(phone);if(x.debugCode)setCode(x.debugCode);notify("验证码已发送")}catch(e){notify(e instanceof Error?e.message:"发送失败")}}}>发送验证码</button></div><button className="confirm" onClick={()=>void login()}>登录 / 自动注册</button></Modal>}
 {personOpen&&<Modal title="添加就诊人" close={()=>setPersonOpen(false)}>{(["name","phone","idCard"] as const).map(k=><label key={k}>{({name:"姓名",phone:"手机号",idCard:"身份证号"})[k]}<input value={personForm[k]} onChange={e=>setPersonForm({...personForm,[k]:e.target.value})}/></label>)}<button className="confirm" onClick={()=>void addPerson()}>保存就诊人</button></Modal>}
 {toast&&<div className="toast"><CheckCircle2/> {toast}</div>}</div></main>}
function Empty({text,children}:{text:string;children?:ReactNode}){return <div className="empty"><Search/><h3>{text}</h3>{children}</div>}
function Modal({title,close,children}:{title:string;close:()=>void;children:ReactNode}){return <div className="modal-backdrop" onClick={close}><div className="booking-sheet form-sheet" onClick={e=>e.stopPropagation()}><div className="modal-handle"/><h2>{title}</h2>{children}</div></div>}
