const base=import.meta.env.VITE_API_BASE_URL??"http://localhost:4000/api/v1";
type Options=RequestInit&{public?:boolean};export type User={userId:number;phone:string;role:string;memberships:{hospitalId:number;hospitalName:string;memberRole:string}[]};
export type Hospital={id:number;code:string;name:string;shortName?:string;level:string;type?:string;province:string;city:string;district:string;address:string;phone?:string};
export type Department={id:number;code:string;name:string;description:string;hospitalId:number;hospitalName:string};export type Doctor={id:number;name:string;title:string;specialty:string;registrationFee:number;hospitalId:number;hospitalName:string;departmentId:number;departmentName:string};
export type Schedule={id:number;scheduleDate:string;period:string;startTime:string;endTime:string;totalSlots:number;bookedSlots:number;availableSlots:number;fee:number;doctorId:number;doctorName:string;hospitalId:number;departmentId:number;departmentName:string};
export type Account={id:number;hospitalId:number;currency:string;balance:number;frozenAmount:number;updatedAt:string};export type Flow={id:number;flowNo:string;businessType:string;direction:string;channel:string;amount:number;balanceAfter:number;status:string;remark?:string;createdAt:string};
export type RegistrationOrder={id:number;orderNo:string;personName:string;personPhone:string;personIdCard:string;doctorName:string;doctorTitle:string;departmentName:string;visitDate:string;period:string;visitNumber:number;amount:number;status:string;createdAt:string;symptoms?:string;cancelReason?:string};
export const session={get:()=>localStorage.getItem("hospital_admin_token"),set:(v:string)=>localStorage.setItem("hospital_admin_token",v),clear:()=>localStorage.removeItem("hospital_admin_token")};
async function request<T>(path:string,options:Options={}):Promise<T>{const headers=new Headers(options.headers);headers.set("Content-Type","application/json");if(!options.public){headers.set("platform","h5");const value=session.get();if(value)headers.set("Authorization",`Bearer ${value}`);}const response=await fetch(`${base}${path}`,{...options,headers});const body=response.status===204?null:await response.json();if(!response.ok)throw new Error(body?.error?.message??"请求失败");return body?.data??body;}
const json=(method:string,data:unknown):RequestInit=>({method,body:JSON.stringify(data)});
export const api={login:async(phone:string,password:string)=>{const data=await request<{accessToken:string;user:Omit<User,"memberships">}>("/auth/password-login",{...json("POST",{phone,password}),public:true});session.set(data.accessToken);return data},me:()=>request<User>("/auth/me"),
 hospitals:()=>request<Hospital[]>("/hospitals?pageSize=100"),addHospital:(d:unknown)=>request("/hospitals",json("POST",d)),updateHospital:(id:number,d:unknown)=>request(`/hospitals/${id}`,json("PATCH",d)),deleteHospital:(id:number)=>request(`/hospitals/${id}`,{method:"DELETE"}),
 departments:(hospitalId:number)=>request<Department[]>(`/departments?hospitalId=${hospitalId}&pageSize=100`),addDepartment:(d:unknown)=>request("/departments",json("POST",d)),updateDepartment:(id:number,d:unknown)=>request(`/departments/${id}`,json("PATCH",d)),deleteDepartment:(id:number)=>request(`/departments/${id}`,{method:"DELETE"}),
 doctors:(hospitalId:number)=>request<Doctor[]>(`/doctors?hospitalId=${hospitalId}&pageSize=100`),addDoctor:(d:unknown)=>request("/doctors",json("POST",d)),updateDoctor:(id:number,d:unknown)=>request(`/doctors/${id}`,json("PATCH",d)),deleteDoctor:(id:number)=>request(`/doctors/${id}`,{method:"DELETE"}),
 schedules:(hospitalId:number)=>request<Schedule[]>(`/schedules?hospitalId=${hospitalId}&pageSize=100`),addSchedule:(d:unknown)=>request("/schedules",json("POST",d)),updateSchedule:(id:number,d:unknown)=>request(`/schedules/${id}`,json("PATCH",d)),deleteSchedule:(id:number)=>request(`/schedules/${id}`,{method:"DELETE"}),
 account:(hospitalId:number)=>request<Account>(`/accounts/${hospitalId}`),flows:(hospitalId:number)=>request<Flow[]>(`/accounts/${hospitalId}/flows?pageSize=100`),recharge:(hospitalId:number,amount:number,remark:string)=>request(`/accounts/${hospitalId}/recharge`,json("POST",{amount,channel:"manual",remark})),
 registrations:(hospitalId:number)=>request<RegistrationOrder[]>(`/merchant/registrations?hospitalId=${hospitalId}&pageSize=100`),registration:(id:number)=>request<RegistrationOrder>(`/merchant/registrations/${id}`),updateRegistrationStatus:(id:number,status:"completed"|"cancelled",reason?:string)=>request(`/merchant/registrations/${id}/status`,json("PATCH",{status,reason}))};
