import{useCallback,useEffect,useState,type FormEvent,type ReactNode}from"react";
import{Activity,CalendarCheck,CalendarDays,ChevronDown,Clock3,CreditCard,LayoutDashboard,LogOut,Menu,Plus,Search,Stethoscope,UsersRound,WalletCards,X}from"lucide-react";
import{api,session,type Account,type Department,type Doctor,type Flow,type Hospital,type Schedule,type User}from"./api";
import OrdersPage from"./OrdersPage";

type Page="工作台"|"预约订单"|"科室管理"|"医生管理"|"医生排班"|"账户管理";
const nav=[{name:"工作台",icon:LayoutDashboard},{name:"预约订单",icon:CalendarCheck},{name:"科室管理",icon:UsersRound},{name:"医生管理",icon:Stethoscope},{name:"医生排班",icon:CalendarDays},{name:"账户管理",icon:WalletCards}]as const;
const period:Record<string,string>={morning:"上午",afternoon:"下午",evening:"晚上",custom:"自定义"};

export default function App(){
 const[user,setUser]=useState<User>(),[phone,setPhone]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[page,setPage]=useState<Page>("工作台"),[open,setOpen]=useState(false),[hospitals,setHospitals]=useState<Hospital[]>([]),[hospitalId,setHospitalId]=useState<number>(),[departments,setDepartments]=useState<Department[]>([]),[doctors,setDoctors]=useState<Doctor[]>([]),[schedules,setSchedules]=useState<Schedule[]>([]),[account,setAccount]=useState<Account>(),[flows,setFlows]=useState<Flow[]>([]),[modal,setModal]=useState<Page>(),[loading,setLoading]=useState(false);
 const bootstrap=useCallback(async()=>{try{const me=await api.me();if(!["merchant_admin","merchant_staff","super_admin"].includes(me.role))throw new Error("当前账号不是医院管理人员");setUser(me);const all=await api.hospitals();const allowed=me.role==="super_admin"?all:all.filter(h=>me.memberships.some(m=>m.hospitalId===h.id));setHospitals(allowed);setHospitalId(x=>x??allowed[0]?.id)}catch(e){session.clear();setUser(undefined);setError(e instanceof Error?e.message:"登录已失效")}},[]);
 useEffect(()=>{if(session.get())void bootstrap()},[bootstrap]);
 const reload=useCallback(async()=>{if(!hospitalId)return;setLoading(true);try{const[d,docs,s,a,f]=await Promise.all([api.departments(hospitalId),api.doctors(hospitalId),api.schedules(hospitalId),api.account(hospitalId),api.flows(hospitalId)]);setDepartments(d);setDoctors(docs);setSchedules(s);setAccount(a);setFlows(f)}catch(e){setError(e instanceof Error?e.message:"加载失败")}finally{setLoading(false)}},[hospitalId]);
 useEffect(()=>{if(user)void reload()},[user,reload]);
 async function login(e:FormEvent){e.preventDefault();setError("");if(!/^1[3-9]\d{9}$/.test(phone))return setError("请输入正确的11位手机号");if(password.length<8)return setError("密码至少8位");try{const result=await api.login(phone,password);if(!["merchant_admin","merchant_staff","super_admin"].includes(result.user.role)){session.clear();throw new Error("该手机号没有医院后台权限")}await bootstrap()}catch(e){setError(e instanceof Error?e.message:"登录失败")}}
 if(!user)return <Login phone={phone} password={password} error={error} setPhone={setPhone} setPassword={setPassword} submit={login}/>;
 const current=hospitals.find(h=>h.id===hospitalId),booked=schedules.reduce((n,s)=>n+s.bookedSlots,0),total=schedules.reduce((n,s)=>n+s.totalSlots,0);
 return <div className="app"><aside className={open?"side open":"side"}><div className="brand"><span><Activity/></span><div>安康医疗<small>医院管理中心</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(n=><button className={page===n.name?"active":""} onClick={()=>{setPage(n.name);setOpen(false)}} key={n.name}><n.icon/>{n.name}</button>)}</nav><div className="side-help"><Clock3/><b>{user.phone}</b><small>{user.role}</small><a onClick={()=>{session.clear();location.reload()}}>退出管理后台</a></div></aside><main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><span>{current?`${current.city} · ${current.district}`:"请选择医院"}</span><b><select value={hospitalId??""} onChange={e=>setHospitalId(Number(e.target.value))}>{hospitals.map(h=><option value={h.id} key={h.id}>{h.name}</option>)}</select><ChevronDown/></b></div><div className="profile"><i>{user.phone.slice(-1)}</i><div><b>{user.phone}</b><small>医院管理账号</small></div><button title="退出" onClick={()=>{session.clear();location.reload()}}><LogOut/></button></div></header><section className="content"><div className="page-title"><div><small>管理控制台 / {page}</small><h1>{page}</h1><p>{loading?"正在同步接口数据…":"所有内容均来自医院挂号服务"}</p></div>{["科室管理","医生管理","医生排班"].includes(page)&&<button className="primary" onClick={()=>setModal(page)}><Plus/>新增</button>}</div>{error&&<div className="admin-error">{error}</div>}{page==="工作台"?<Dashboard doctors={doctors} schedules={schedules} account={account} booked={booked} total={total} setPage={setPage}/>:page==="预约订单"&&hospitalId?<OrdersPage hospitalId={hospitalId}/>:<DataPage page={page} departments={departments} doctors={doctors} schedules={schedules} account={account} flows={flows} onDelete={async(kind,id)=>{if(!confirm("确认删除这条记录？"))return;try{if(kind==="department")await api.deleteDepartment(id);if(kind==="doctor")await api.deleteDoctor(id);if(kind==="schedule")await api.deleteSchedule(id);await reload()}catch(e){setError(e instanceof Error?e.message:"删除失败")}}} onRecharge={async amount=>{try{await api.recharge(hospitalId!,amount,"医院后台充值");await reload()}catch(e){setError(e instanceof Error?e.message:"充值失败")}}}/>}</section></main>{modal&&<CreateModal page={modal} hospitalId={hospitalId!} departments={departments} doctors={doctors} close={()=>setModal(undefined)} done={async()=>{setModal(undefined);await reload()}} fail={setError}/>}</div>
}

function Login(p:{phone:string;password:string;error:string;setPhone:(x:string)=>void;setPassword:(x:string)=>void;submit:(e:FormEvent)=>void}){return <div className="login-page"><form className="login-card" onSubmit={p.submit}><div className="login-logo"><Activity/></div><span className="eyebrow">HOSPITAL CONSOLE</span><h1>医院管理中心</h1><p>仅限已分配账号的医院管理员和员工登录，不开放注册</p><label>手机号<input type="tel" inputMode="numeric" value={p.phone} onChange={e=>p.setPhone(e.target.value.replace(/\D/g,"").slice(0,11))} placeholder="请输入11位管理员手机号" required/></label><label>登录密码<input type="password" value={p.password} onChange={e=>p.setPassword(e.target.value)} placeholder="请输入登录密码" minLength={8} maxLength={72} required/></label>{p.error&&<div className="admin-error">{p.error}</div>}<button className="login-submit">登录管理后台</button></form></div>}
function Dashboard({doctors,schedules,account,booked,total,setPage}:{doctors:Doctor[];schedules:Schedule[];account?:Account;booked:number;total:number;setPage:(p:Page)=>void}){const available=Math.max(total-booked,0);return <><div className="stats"><Stat icon={CalendarDays} tone="blue" label="有效排班" value={schedules.length}/><Stat icon={Stethoscope} tone="green" label="在职医生" value={doctors.length}/><Stat icon={UsersRound} tone="orange" label="剩余号源" value={available}/><Stat icon={CreditCard} tone="purple" label="账户余额" value={`¥ ${Number(account?.balance??0).toFixed(2)}`}/></div><div className="quick panel">{nav.slice(1).map(n=><button key={n.name} onClick={()=>setPage(n.name)}><n.icon/><span>{n.name}</span><small>立即管理 →</small></button>)}</div><article className="panel"><div className="panel-head"><div><h2>有效排班</h2><p>医生、日期与剩余号源</p></div></div><ScheduleTable data={schedules}/></article></>}
function Stat({icon:Icon,tone,label,value}:{icon:typeof CalendarDays;tone:string;label:string;value:string|number}){return <article><span className={tone}><Icon/></span><small>{label}</small><strong>{value}</strong><em>实时接口数据</em></article>}
function DataPage(p:{page:Page;departments:Department[];doctors:Doctor[];schedules:Schedule[];account?:Account;flows:Flow[];onDelete:(k:string,id:number)=>void;onRecharge:(n:number)=>void}){if(p.page==="账户管理")return <><div className="account"><div><small>账户可用余额</small><strong>¥ {Number(p.account?.balance??0).toFixed(2)}</strong><p>冻结金额 ¥ {Number(p.account?.frozenAmount??0).toFixed(2)}</p></div><button onClick={()=>{const n=Number(prompt("请输入充值金额"));if(n>0)p.onRecharge(n)}}>充值</button></div><article className="panel"><Table heads={["流水号","业务类型","金额","渠道","状态","时间"]}>{p.flows.map(f=><tr key={f.id}><td>{f.flowNo}</td><td>{f.businessType}</td><td className={f.direction==="expense"?"minus":"money"}>{f.direction==="expense"?"-":"+"} ¥ {f.amount}</td><td>{f.channel}</td><td><span className="badge">{f.status}</span></td><td>{new Date(f.createdAt).toLocaleString()}</td></tr>)}</Table>{!p.flows.length&&<Empty/>}</article></>;if(p.page==="科室管理")return <article className="panel"><Table heads={["科室","编号","所属医院","说明","操作"]}>{p.departments.map(d=><tr key={d.id}><td><b>{d.name}</b></td><td>{d.code}</td><td>{d.hospitalName}</td><td>{d.description||"-"}</td><td><button className="link danger" onClick={()=>p.onDelete("department",d.id)}>删除</button></td></tr>)}</Table>{!p.departments.length&&<Empty/>}</article>;if(p.page==="医生管理")return <article className="panel"><Table heads={["医生","科室 / 职称","擅长","挂号费","操作"]}>{p.doctors.map(d=><tr key={d.id}><td><div className="doctor"><i>{d.name[0]}</i><b>{d.name}</b></div></td><td>{d.departmentName}<small>{d.title}</small></td><td>{d.specialty}</td><td>¥ {d.registrationFee}</td><td><button className="link danger" onClick={()=>p.onDelete("doctor",d.id)}>删除</button></td></tr>)}</Table>{!p.doctors.length&&<Empty/>}</article>;return <article className="panel"><ScheduleTable data={p.schedules} onDelete={id=>p.onDelete("schedule",id)}/>{!p.schedules.length&&<Empty/>}</article>}
function ScheduleTable({data,onDelete}:{data:Schedule[];onDelete?:(id:number)=>void}){const[rows,setRows]=useState(data),[editing,setEditing]=useState<Schedule>();useEffect(()=>setRows(data),[data]);const formatDate=(value:string)=>{const m=String(value).match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}年${Number(m[2])}月${Number(m[3])}日`:"日期待定"};async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!editing)return;const d=Object.fromEntries(new FormData(e.currentTarget)),p=String(d.period),times=p==="morning"?["08:00","12:00"]:["13:00","18:00"],update={scheduleDate:String(d.date),period:p,startTime:times[0],endTime:times[1],totalSlots:Number(d.totalSlots),fee:Number(d.fee)};await api.updateSchedule(editing.id,update);setRows(x=>x.map(s=>s.id===editing.id?{...s,...update}:s));setEditing(undefined)}return <><Table heads={["医生","科室","日期 / 时段","号源","费用","操作"]}>{rows.map(s=><tr key={s.id}><td><b>{s.doctorName}</b></td><td>{s.departmentName}</td><td>{formatDate(s.scheduleDate)} · {period[s.period]??s.period}<small>{String(s.startTime).slice(0,5)}–{String(s.endTime).slice(0,5)}</small></td><td>{s.bookedSlots} / {s.totalSlots}</td><td>¥ {s.fee}</td><td>{onDelete&&<div className="row-actions">{s.bookedSlots===0?<button className="link" onClick={()=>setEditing(s)}>修改</button>:<small>已有预约，不可修改</small>}<button className="link danger" onClick={()=>onDelete(s.id)}>删除</button></div>}</td></tr>)}</Table>{editing&&<div className="mask" onClick={()=>setEditing(undefined)}><form className="modal" onSubmit={save} onClick={e=>e.stopPropagation()}><button type="button" className="close" onClick={()=>setEditing(undefined)}><X/></button><span className="eyebrow">EDIT SCHEDULE</span><h2>修改医生排班</h2><p>{editing.doctorName} · {editing.departmentName}</p><Field n="date" l="排班日期" type="date" defaultValue={String(editing.scheduleDate).slice(0,10)}/><label>时段<select name="period" defaultValue={editing.period}><option value="morning">上午（08:00–12:00）</option><option value="afternoon">下午（13:00–18:00）</option></select></label><Field n="totalSlots" l="号源数" type="number" defaultValue={String(editing.totalSlots)}/><Field n="fee" l="挂号费" type="number" defaultValue={String(editing.fee)}/><div className="actions"><button type="button" onClick={()=>setEditing(undefined)}>取消</button><button className="primary">保存修改</button></div></form></div>}</>}
function Table({heads,children}:{heads:string[];children:ReactNode}){return <div className="table-wrap"><table><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{children}</tbody></table></div>}
function Empty(){return <div className="admin-empty"><Search/><p>暂无接口数据</p></div>}
function CreateModal({page,hospitalId,departments,doctors,close,done,fail}:{page:Page;hospitalId:number;departments:Department[];doctors:Doctor[];close:()=>void;done:()=>void;fail:(x:string)=>void}){const today=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10);const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.currentTarget));try{if(page==="科室管理")await api.addDepartment({hospitalId,code:d.code,name:d.name,description:d.description,sortOrder:0});if(page==="医生管理")await api.addDoctor({hospitalId,departmentId:Number(d.departmentId),name:d.name,title:d.title,specialty:d.specialty,registrationFee:Number(d.fee),sortOrder:0});if(page==="医生排班"){const base={doctorId:Number(d.doctorId),scheduleDate:d.date,totalSlots:Number(d.totalSlots),fee:Number(d.fee)};if(d.period==="full")await Promise.all([api.addSchedule({...base,period:"morning",startTime:"08:00",endTime:"12:00"}),api.addSchedule({...base,period:"afternoon",startTime:"13:00",endTime:"18:00"})]);else{const morning=d.period==="morning";await api.addSchedule({...base,period:d.period,startTime:morning?"08:00":"13:00",endTime:morning?"12:00":"18:00"})}}await done()}catch(e){fail(e instanceof Error?e.message:"保存失败")}};return <div className="mask" onClick={close}><form className="modal" onSubmit={submit} onClick={e=>e.stopPropagation()}><button type="button" className="close" onClick={close}><X/></button><span className="eyebrow">CREATE</span><h2>新增{page.replace("管理","")}</h2>{page==="科室管理"&&<><Field n="name" l="科室名称"/><Field n="code" l="科室编码"/><Field n="description" l="科室说明"/></>}{page==="医生管理"&&<><Field n="name" l="医生姓名"/><Field n="title" l="职称"/><Field n="specialty" l="擅长"/><Field n="fee" l="挂号费" type="number"/><label>所属科室<select name="departmentId">{departments.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label></>}{page==="医生排班"&&<><label>医生<select name="doctorId">{doctors.map(d=><option value={d.id} key={d.id}>{d.name}</option>)}</select></label><Field n="date" l="排班日期" type="date" defaultValue={today}/><label>时段<select name="period" defaultValue="morning"><option value="morning">上午（08:00–12:00）</option><option value="afternoon">下午（13:00–18:00）</option><option value="full">全天（自动创建上午、下午）</option></select></label><Field n="totalSlots" l="每个时段号源数" type="number" defaultValue="30"/><Field n="fee" l="挂号费" type="number" defaultValue="50"/></>}<div className="actions"><button type="button" onClick={close}>取消</button><button className="primary">确认保存</button></div></form></div>}
function Field({n,l,type="text",defaultValue}:{n:string;l:string;type?:string;defaultValue?:string}){return <label>{l}<input name={n} type={type} defaultValue={defaultValue} required/></label>}
