import {useState} from "react";import {Activity,Building2,CalendarDays,ChevronDown,Clock3,CreditCard,LayoutDashboard,Menu,Plus,Search,Stethoscope,UsersRound,WalletCards,X} from "lucide-react";
type Page="工作台"|"医院管理"|"科室管理"|"医生管理"|"医生排班"|"账户管理";
const nav=[{name:"工作台",icon:LayoutDashboard},{name:"医院管理",icon:Building2},{name:"科室管理",icon:UsersRound},{name:"医生管理",icon:Stethoscope},{name:"医生排班",icon:CalendarDays},{name:"账户管理",icon:WalletCards}] as const;
const depts=[{name:"心血管内科",code:"CV-001",doctors:18,status:"正常"},{name:"皮肤科",code:"DER-002",doctors:12,status:"正常"},{name:"儿科",code:"PED-003",doctors:15,status:"正常"},{name:"中医科",code:"TCM-004",doctors:9,status:"停用"}];
const doctors=[{name:"张明远",title:"主任医师",dept:"心血管内科",schedule:"今日 08:00–12:00",slots:"16 / 30"},{name:"林书雅",title:"副主任医师",dept:"皮肤科",schedule:"明日 13:30–17:30",slots:"8 / 24"},{name:"周启航",title:"主治医师",dept:"儿科",schedule:"今日 13:30–17:30",slots:"21 / 25"},{name:"陈若溪",title:"主任医师",dept:"中医科",schedule:"周五 08:00–12:00",slots:"5 / 20"}];
function App(){const[page,setPage]=useState<Page>("工作台");const[open,setOpen]=useState(false);const[modal,setModal]=useState(false);return <div className="app">
<aside className={open?"side open":"side"}><div className="brand"><span><Activity/></span><div>青禾医疗<small>医院管理中心</small></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(n=><button className={page===n.name?"active":""} onClick={()=>{setPage(n.name);setOpen(false)}} key={n.name}><n.icon/>{n.name}</button>)}</nav><div className="side-help"><Clock3/><b>需要帮助？</b><small>服务时间 08:00–22:00</small><a>联系平台客服</a></div></aside>
<main><header><button className="menu" onClick={()=>setOpen(true)}><Menu/></button><div><span>北京市 · 朝阳区</span><b>北京青禾综合医院 <ChevronDown/></b></div><div className="profile"><i>王</i><div><b>王院长</b><small>医院管理员</small></div><ChevronDown/></div></header>
<section className="content"><div className="page-title"><div><small>管理控制台 / {page}</small><h1>{page}</h1><p>{page==="工作台"?"掌握医院运营、号源与账户的实时状态":"管理医院业务资料，所有修改将同步到挂号端"}</p></div>{page!=="工作台"&&<button className="primary" onClick={()=>setModal(true)}><Plus/>新增{page.replace("管理","").replace("医生排班","排班")}</button>}</div>
{page==="工作台"?<Dashboard setPage={setPage}/>:<DataPage page={page}/>}</section></main>
{modal&&<div className="mask" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}><X/></button><span className="eyebrow">NEW RECORD</span><h2>新增{page.replace("管理","")}</h2><p>请填写基本信息，保存后可继续完善详细资料。</p><label>名称<input placeholder="请输入名称"/></label><label>所属医院<select><option>北京青禾综合医院</option></select></label><label>备注<textarea placeholder="选填"/></label><div className="actions"><button onClick={()=>setModal(false)}>取消</button><button className="primary" onClick={()=>setModal(false)}>确认保存</button></div></div></div>}</div>}
function Dashboard({setPage}:{setPage:(p:Page)=>void}){return <><div className="stats"><article><span className="blue"><CalendarDays/></span><small>今日预约</small><strong>286</strong><em>较昨日 +12.8%</em></article><article><span className="green"><Stethoscope/></span><small>在诊医生</small><strong>42</strong><em>共 68 名医生</em></article><article><span className="orange"><UsersRound/></span><small>剩余号源</small><strong>1,248</strong><em>号源利用率 72%</em></article><article><span className="purple"><CreditCard/></span><small>本月挂号收入</small><strong>¥ 86,420</strong><em>较上月 +8.4%</em></article></div><div className="grid"><article className="panel grow"><div className="panel-head"><div><h2>近 7 日预约趋势</h2><p>每日挂号量与完成量</p></div><select><option>最近 7 天</option></select></div><div className="chart"><div className="bars">{[45,62,52,78,66,88,72].map((v,i)=><i key={i} style={{height:v+"%"}}><b style={{height:(v-15)+"%"}}/></i>)}</div><div className="days"><span>周一</span><span>周二</span><span>周三</span><span>周四</span><span>周五</span><span>周六</span><span>周日</span></div></div></article><article className="panel"><div className="panel-head"><div><h2>快捷操作</h2><p>常用管理入口</p></div></div><div className="quick">{nav.slice(2).map(n=><button key={n.name} onClick={()=>setPage(n.name)}><n.icon/><span>{n.name}</span><small>立即管理 →</small></button>)}</div></article></div><article className="panel"><div className="panel-head"><div><h2>今日排班概览</h2><p>当前医院重点排班与号源状态</p></div><button className="text" onClick={()=>setPage("医生排班")}>查看全部</button></div><DoctorTable/></article></>}
function DataPage({page}:{page:Page}){if(page==="账户管理")return <><div className="account"><div><small>账户可用余额</small><strong>¥ 268,420.00</strong><p>冻结金额 ¥ 12,800.00</p></div><button>充值</button></div><article className="panel"><div className="panel-head"><div><h2>资金流水</h2><p>充值、冻结、消费与退款记录</p></div></div><table><thead><tr><th>流水号</th><th>业务类型</th><th>金额</th><th>渠道</th><th>状态</th><th>时间</th></tr></thead><tbody>{["FLOW20260713001","FLOW20260712018","FLOW20260711009"].map((x,i)=><tr><td>{x}</td><td>{["充值","消费","退款"][i]}</td><td className={i===1?"minus":"money"}>{i===1?"- ¥ 120.00":"+ ¥ "+["20,000.00","","60.00"][i]}</td><td>微信支付</td><td><span className="badge">成功</span></td><td>2026-07-{13-i} 10:28</td></tr>)}</tbody></table></article></>;
return <article className="panel"><div className="toolbar"><div className="search"><Search/><input placeholder={`搜索${page.replace("管理","")}名称、编号`}/></div><select><option>全部状态</option><option>正常</option><option>停用</option></select></div>{page.includes("医生")?<DoctorTable/>:<table><thead><tr><th>科室名称</th><th>科室编号</th><th>医生数</th><th>状态</th><th>操作</th></tr></thead><tbody>{depts.map(d=><tr><td><b>{d.name}</b></td><td>{d.code}</td><td>{d.doctors} 人</td><td><span className={d.status==="正常"?"badge":"badge off"}>{d.status}</span></td><td><button className="link">编辑</button><button className="link danger">删除</button></td></tr>)}</tbody></table>}</article>}
function DoctorTable(){return <div className="table-wrap"><table><thead><tr><th>医生</th><th>科室 / 职称</th><th>最近排班</th><th>已约 / 总号源</th><th>状态</th><th>操作</th></tr></thead><tbody>{doctors.map((d,i)=><tr key={d.name}><td><div className="doctor"><i>{d.name[0]}</i><b>{d.name}</b></div></td><td>{d.dept}<small>{d.title}</small></td><td>{d.schedule}</td><td>{d.slots}</td><td><span className={i===3?"badge warn":"badge"}>{i===3?"待排班":"接诊中"}</span></td><td><button className="link">管理排班</button></td></tr>)}</tbody></table></div>}
export default App;
