import{useCallback,useEffect,useState}from"react";
import{CalendarCheck,Eye,Search,X}from"lucide-react";
import{api,type RegistrationOrder}from"./api";

const statusText:Record<string,string>={pending_payment:"已预约",paid:"已付款",confirmed:"待就诊",completed:"已完成",cancelled:"已取消",refunded:"已退款",expired:"已过期"};
const periodText:Record<string,string>={morning:"上午",afternoon:"下午",evening:"晚上",custom:"其他"};
const visitTime=(date:string,period:string)=>{const m=String(date).match(/^(\d{4})-(\d{1,2})-(\d{1,2})/);return m?`${m[1]}年${Number(m[2])}月${Number(m[3])}日 ${periodText[period]??period}`:"日期待定"};

export default function OrdersPage({hospitalId}:{hospitalId:number}){const[orders,setOrders]=useState<RegistrationOrder[]>([]),[detail,setDetail]=useState<RegistrationOrder>(),[loading,setLoading]=useState(false),[error,setError]=useState("");const load=useCallback(async()=>{setLoading(true);try{setOrders(await api.registrations(hospitalId))}catch(e){setError(e instanceof Error?e.message:"订单加载失败")}finally{setLoading(false)}},[hospitalId]);useEffect(()=>{void load()},[load]);async function open(id:number){try{setDetail(await api.registration(id))}catch(e){setError(e instanceof Error?e.message:"详情加载失败")}}async function update(status:"completed"|"cancelled"){if(!detail)return;const reason=status==="cancelled"?(prompt("请输入取消原因","医院取消")||"医院取消"):undefined;if(status==="cancelled"&&!confirm("确认取消该预约？号源将自动释放。"))return;if(status==="completed"&&!confirm("确认将该预约标记为已完成？"))return;try{await api.updateRegistrationStatus(detail.id,status,reason);setDetail(undefined);await load()}catch(e){setError(e instanceof Error?e.message:"状态更新失败")}}
return <>{error&&<div className="admin-error">{error}</div>}<article className="panel"><div className="panel-head"><div><h2>预约订单</h2><p>{loading?"正在加载…":`共 ${orders.length} 条医院预约记录`}</p></div></div><div className="table-wrap"><table><thead><tr>{["姓名","手机号","身份证号","医生","科室","预约时间","状态","操作"].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.personName}</b></td><td>{o.personPhone}</td><td>{o.personIdCard}</td><td>{o.doctorName}<small>{o.doctorTitle}</small></td><td>{o.departmentName}</td><td>{visitTime(o.visitDate,o.period)}</td><td><span className={`badge status-${o.status}`}>{statusText[o.status]??o.status}</span></td><td><button className="link order-view" onClick={()=>void open(o.id)}><Eye/>管理</button></td></tr>)}</tbody></table></div>{!loading&&!orders.length&&<div className="admin-empty"><Search/><p>暂无预约订单</p></div>}</article>{detail&&<div className="mask" onClick={()=>setDetail(undefined)}><section className="modal order-modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(undefined)}><X/></button><span className="eyebrow">REGISTRATION DETAIL</span><h2>预约详情</h2><div className="order-status"><CalendarCheck/><div><b>{statusText[detail.status]??detail.status}</b><small>订单号 {detail.orderNo}</small></div></div><dl className="detail-grid"><dt>就诊人姓名</dt><dd>{detail.personName}</dd><dt>手机号</dt><dd>{detail.personPhone}</dd><dt>身份证号</dt><dd>{detail.personIdCard}</dd><dt>预约医生</dt><dd>{detail.doctorName} · {detail.doctorTitle}</dd><dt>就诊科室</dt><dd>{detail.departmentName}</dd><dt>预约时间</dt><dd>{visitTime(detail.visitDate,detail.period)}</dd><dt>就诊序号</dt><dd>{detail.visitNumber||"待分配"}</dd><dt>挂号费用</dt><dd>¥ {Number(detail.amount).toFixed(2)}</dd></dl>{["pending_payment","paid","confirmed"].includes(detail.status)&&<div className="actions"><button className="danger-action" onClick={()=>void update("cancelled")}>取消预约</button><button className="primary" onClick={()=>void update("completed")}>完成就诊</button></div>}</section></div>}</>}
