<script setup lang="ts">
import{computed,onMounted,ref}from"vue";import{useRoute,useRouter}from"vue-router";import{ChevronDown,Plus,ShieldCheck,UserRound}from"lucide-vue-next";import{api,type Doctor,type Hospital,type Person,type Schedule}from"../api";import PageHeader from"../components/PageHeader.vue";
const route=useRoute(),router=useRouter(),doctor=ref<Doctor>(),hospital=ref<Hospital>(),schedule=ref<Schedule>(),people=ref<Person[]>([]),personId=ref<number>(),adding=ref(false),name=ref(""),phone=ref(""),idCard=ref(""),rulesOpen=ref(false),agree=ref(false),message=ref("");
const selectedPerson=computed(()=>people.value.find(p=>p.id===personId.value));const newPersonValid=computed(()=>name.value.trim().length>=2&&/^1[3-9]\d{9}$/.test(phone.value)&&/^(\d{15}|\d{17}[0-9Xx])$/.test(idCard.value));const valid=computed(()=>Boolean((selectedPerson.value||newPersonValid.value)&&agree.value));const dateText=computed(()=>{if(!schedule.value)return"";const d=new Date(`${schedule.value.scheduleDate}T00:00:00`);const part={morning:"上午",afternoon:"下午",evening:"晚上",custom:"其他"}[schedule.value.period]??schedule.value.period;return`${d.getFullYear()} 年 ${d.getMonth()+1} 月 ${d.getDate()} 日 ${part}`});const locationText=computed(()=>hospital.value?`${hospital.value.province}${hospital.value.city}${hospital.value.district}${hospital.value.address} · ${doctor.value?.departmentName}（具体楼层以院内导诊为准）`:"");
onMounted(async()=>{const did=Number(route.params.doctorId),sid=Number(route.params.scheduleId);doctor.value=await api.doctor(did);[hospital.value,people.value]=await Promise.all([api.hospital(doctor.value.hospitalId),api.people()]);schedule.value=(await api.schedules(did)).find(x=>x.id===sid);personId.value=(people.value.find(x=>x.isDefault)||people.value[0])?.id;adding.value=!people.value.length});
function showAdd(){adding.value=true;personId.value=undefined;name.value="";phone.value=localStorage.getItem("patient_phone")||"";idCard.value=""}
async function submit(){if(!valid.value||!doctor.value||!schedule.value)return;try{let pid=personId.value;if(!pid){const p=await api.addPerson({name:name.value.trim(),phone:phone.value,idCard:idCard.value.toUpperCase(),relationship:"self",isDefault:people.value.length===0});pid=p.id}const o=await api.register({registrationPersonId:pid,hospitalId:doctor.value.hospitalId,departmentId:doctor.value.departmentId,doctorId:doctor.value.id,scheduleId:schedule.value.id});router.replace(`/orders/${o.id}`)}catch(e){message.value=e instanceof Error?e.message:"预约失败"}}
</script>
<template><main v-if="doctor&&schedule" class="booking-page"><PageHeader title="确认预约"/><section class="booking-doctor"><div class="avatar">{{doctor.name[0]}}</div><div><h2>{{doctor.name}} <small>{{doctor.title}} · {{doctor.departmentName}}</small></h2><p>{{doctor.hospitalName}}</p></div></section><section class="booking-card"><h3>号源信息</h3><dl><dt>日期</dt><dd>{{dateText}}</dd><dt>医院</dt><dd>{{doctor.hospitalName}}</dd><dt>地点</dt><dd>{{locationText}}</dd><dt>费用</dt><dd class="price">¥{{schedule.fee}}（到院支付）</dd></dl><small>挂号费由医院自行设定，平台不收取额外费用</small></section><section class="booking-card patient-info"><header><h3>预约信息</h3><button @click="showAdd"><Plus/>添加就诊人</button></header><div v-if="people.length&&!adding" class="person-picker"><button v-for="p in people" :key="p.id" :class="{active:personId===p.id}" @click="personId=p.id"><UserRound/><div><b>{{p.name}}</b><small>{{p.phone}} · {{p.idCardMasked}}</small></div><i v-if="p.isDefault">默认</i></button></div><div v-else class="patient-form"><label>姓名<input v-model="name" placeholder="请输入就诊人姓名"/></label><label>手机号<input :value="phone" @input="phone=($event.target as HTMLInputElement).value.replace(/\D/g,'').slice(0,11)" inputmode="numeric" placeholder="请输入11位手机号"/></label><label>身份证号<input :value="idCard" @input="idCard=($event.target as HTMLInputElement).value.replace(/[^0-9Xx]/g,'').slice(0,18)" placeholder="15位或18位身份证号"/></label><p v-if="idCard&&!/^(\d{15}|\d{17}[0-9Xx])$/.test(idCard)" class="form-message">身份证号格式不正确</p><button v-if="people.length" class="text-button" @click="adding=false;personId=people[0].id">选择已有就诊人</button></div></section><section class="booking-card rules"><button @click="rulesOpen=!rulesOpen"><b>预约规则</b><ChevronDown :class="{rotate:rulesOpen}"/></button><div :class="{clamped:!rulesOpen}"><p>* 专家门诊资源有限，如预约成功后不能按时就诊，请尽早取消。</p><p>* 网上挂号实行实名制，请填写真实姓名、手机号和身份证号。</p><p>* 就诊时请携带身份证、医保卡，并提前到院取号。</p></div></section><div class="booking-bottom"><label><input type="checkbox" v-model="agree"/>我已阅读并同意预约规则</label><p v-if="message" class="form-message center">{{message}}</p><button :disabled="!valid" @click="submit"><ShieldCheck/>立即挂号</button></div></main></template>
